### PR TITLE
Sphinx

### PR DESCRIPTION
**Pull request by toniSta**
Docu can be generated by `documentation.sh` (might only run under Ubuntu !)
Hosted on readthedocs [here](http://blockchain-vaccination-records.readthedocs.io/en/latest/blockchain.helper.html)

### CODE REVIEW

**Comment by toniSta** [comment]
Currently, the auto generator can't deal with nested classes. This is needed for documentation of our singletons. Any ideas?

**Comment by Benedikt1992** [comment]
On the topic about nested classes. Unfortunately currently no idea.

Why are you recreating the whole sphinx project in the script? Was there some issue?

**Comment by toniSta** [comment]
I had to recreate it a couple of times, when I set it up. However, I wanted to share, what I did.

**Comment by Benedikt1992** [comment]
This means the script doesn't need to be run every time? In this case I would remove it before merging. (Anyway thanks for sharing)

**Comment by Benedikt1992** [comment]
@toniSta I had a look in the inner class problem. It is not solveable. In order to include the docstrings `sphinx` won't parse the source files. It will actually load the module and call `help()` to get the docstrings. Therefore it's not possible for sphinx to load and get docstrings from private inner classes like `Chain.__Chain`.

Only workaround would be to change the inner classes from `private` to `protected`. I don't think we should do that. There are reasons why the singleton has a private inner class. I added a notice in the readme about this issue.

**Pull request merged**
